=== aeronautical-informatics/ODME/Dynamic/InitScenario/ses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
    
        <xs:complexType name="aspectType">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="entity"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="multiAspectType">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="entity"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
        <xs:attribute name="constraint" use="optional"/>
    </xs:complexType>

    <xs:complexType name="specializationType">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="entity"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
    </xs:complexType>


    <xs:complexType name="varType"> 
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="entity"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
        <xs:attribute name="type" use="optional"/>
        <xs:attribute name="default" use="optional"/>
        <xs:attribute name="lower" use="optional"/>
        <xs:attribute name="upper" use="optional"/>
        
    </xs:complexType>


    <xs:element name="entity">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="aspect"/>
                    <xs:element ref="specialization"/>
                    <xs:element ref="multiAspect"/>
                    <xs:element ref="var"/>
                    
                </xs:choice>            
                
            </xs:sequence>

            <xs:attribute name="name" use="required"/>
            <xs:attribute name="ref" use="optional"/>
          
            <xs:assert test="every $x in .//entity satisfies empty($x//*[@name = $x/@name])"/> 
            <xs:assert test="every $x in .//entity satisfies count(*[$x/@name = $x/following-sibling::*/@name]) = 0"/>                
            <xs:assert test="every $x in .//var satisfies count(*[@name = following-sibling::*/@name]) = 0"/>                                     
            
        </xs:complexType>      
        
      
    </xs:element>

    <xs:element name="aspect" type="aspectType"/>
    <xs:element name="multiAspect" type="multiAspectType"/>
    <xs:element name="specialization" type="specializationType"/>
    <xs:element name="var" type="varType"/>   

     
</xs:schema>

=== aeronautical-informatics/ODME/Dynamic/ScenarioDynamic/xmlforxsd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<entity xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ses.xsd" name="Scenario">
<aspect name="scenarioDec">
<entity name="Environment">
<aspect name="envDec">
<entity name="Summer_Season">
</entity>
<entity name="Noon_TimeOfDay">
</entity>
</aspect>
</entity>
<entity name="EgoAC">
<var name="Latitude" default="64" lower="63.7" upper="65" ></var>
<var name="Longitude" default="-22.60" lower="-22.65" upper="-21.50" ></var>
<var name="Altitude" default="1500" lower="1400" upper="1600" ></var>
<var name="Plane_Distance" default="none" lower="100" upper="600" ></var>
<var name="Roll" default="none" lower="-30" upper="30" ></var>
<var name="Pitch" default="none" lower="-30" upper="30" ></var>
<var name="Yaw" default="none" lower="0" upper="360" ></var>
</entity>
<entity name="B737_300_IntruderAC">
<var name="Latitude" default="none" lower="63.7" upper="65" ></var>
<var name="Longitude" default="none" lower="-22.6" upper="-21.5" ></var>
<var name="Altitude" default="none" lower="700" upper="1300" ></var>
</entity>
</aspect>
</entity>

=== aeronautical-informatics/ODME/Dynamic/ACLatitude/xmlforxsd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<entity xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ses.xsd" name="Scenario">
<aspect name="scenarioDec">
<entity name="Environment">
<aspect name="envDec">
<entity name="Season">
<specialization name="seasonSpec">
<entity name="Summer">
</entity>
<entity name="Winter">
</entity>
</specialization>
</entity>
<entity name="TimeOfDay">
<specialization name="ToDSpec">
<entity name="Dawn">
</entity>
<entity name="Morning">
</entity>
<entity name="Noon">
</entity>
<entity name="Afternoon">
</entity>
<entity name="Dusk">
</entity>
</specialization>
</entity>
</aspect>
</entity>
<entity name="EgoAC">
<var name="Latitude" default="64" lower="63.7" upper="65" ></var>
<var name="Longitude" default="-22.60" lower="-22.65" upper="-21.50" ></var>
<var name="Plane_Distance" default="none" lower="100" upper="600" ></var>
<var name="Roll" default="none" lower="-30" upper="30" ></var>
<var name="Pitch" default="none" lower="-30" upper="30" ></var>
<var name="Yaw" default="none" lower="0" upper="360" ></var>
<var name="Altitude" default="none" lower="700" upper="1300" ></var>
</entity>
<entity name="IntruderAC">
<var name="Latitude" default="63.9" lower="63.7" upper="65" ></var>
<var name="Longitude" default="none" lower="-22.6" upper="-21.5" ></var>
<var name="Altitude" default="none" lower="700" upper="1300" ></var>
<specialization name="IACSpec">
<entity name="B737_300">
</entity>
<entity name="B787_8">
</entity>
<entity name="A340_600">
</entity>
</specialization>
</entity>
</aspect>
</entity>
